name: EDA Notebook Check

on:
  push:
    branches:
      - main
      - task-1
  pull_request:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run notebook
      run: |
        pip install jupyter nbconvert
        jupyter nbconvert --execute --inplace notebooks/eda.ipynb
